name: upper-build
on: 
    push:
        paths:
            - ".github/workflows/upper-build.yaml"
            - "upper/**"
    workflow_dispatch: 
        
jobs:
    build:
        runs-on: macos-latest
        steps:
            - run: pwd && ls -al
            
            - uses: actions/checkout@v4 #checkout the code repo
            
            - run: pwd && ls -al
            
            #- run: go version
            
            - uses: actions/setup-go@v5
              with:
                go-version: '1.24.13'
                cache-dependency-path: upper/go.sum
                
            - run: go mod download
              working-directory: ./upper      
              
            - name: Build and Test Upper  
              run: |
                ls
                go build
                ls
                go test
                ./upper foo the bar
              working-directory: ./upper