name: upper-build-3
on: 
    push:
        paths:
            - "github/workflows/upper-build.yaml"
            - "upper/**"

   
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - run: go version
            - run: cat Dockerfile

            
              